import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/contexts/theme-context";
import ClientInitializer from "./components/ClientInitializer";

// 必要なフォントのみを保持し、display: swapで最適化
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja" suppressHydrationWarning>
      <body
        className={`
          relative min-h-screen
          ${geistSans.variable}
          antialiased
        `}
      >
        <ThemeProvider>
          <ClientInitializer />
          <div className="absolute inset-0 bg-[url('/images/Welcome-background.png')] bg-cover bg-center bg-no-repeat dark:opacity-80" />
          <div className="absolute inset-0 bg-white bg-opacity-40 dark:bg-gray-900 dark:bg-opacity-70" />
          <div className="relative z-10">{children}</div>
        </ThemeProvider>
      </body>
    </html>
  );
}
