services:
  backend-go:
    build: backend-go
    volumes:
      - ./backend-go/srcs/:/usr/src/app/srcs
    tty: true
  db-mysql:
    build: db-mysql
    ports:
      - "3306:3306"
    volumes:
      - ./db-mysql/data/:/var/lib/db-mysql
      - ./db-mysql/configs/:/etc/db-mysql/conf.d/
      - ./db-mysql/logs:/var/log/db-mysql
    env_file:
      - .env