services:
  backend-go:
    build: backend-go
    volumes:
      - ./backend-go/srcs/:/usr/src/app/srcs
    env_file:
      - .env
    tty: true
  db-mysql:
    build:
      context: ./db-mysql
      args:
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_USER_PASSWORD: ${MYSQL_USER_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./db-mysql/data/:/var/lib/mysql
      - ./db-mysql/logs:/var/log/mysql
    env_file:
      - .env