// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs


/*
  ユーザーテーブル
*/
Table t_users {
  id integer [primary key]
  username varchar(30) [unique]
  email varchar(255) [unique]
  password varchar(60)
  display_name varchar(20)
  icon_image_url varchar(255)
  introduction varchar(200)
  town_name varchar(30)
  coin_count integer
  created_at timestamp
}


/*
  作業内容
*/
Table t_works {
  id integer [primary key]
  user_id integer [not null, ref: > t_users.id]
  work_name varchar(60) [not null]
  icon_image_url varchar(255)
}


/*
  作業ログ
*/
Table t_work_logs {
  id integer [primary key]
  user_id integer [not null, ref: > t_users.id]
  work_id integer [not null, ref: > t_works.id]
  start_at timestamp [not null]
  minutes bigint [not null]
}

