// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs


/*
  ユーザーテーブル
*/
Table t_users {
  id integer [primary key]
  username varchar(30) [unique]
  email varchar(255) [unique]
  password varchar(60)
  display_name varchar(20)
  icon_image_url varchar(255)
  created_at timestamp
  updated_at timestamp
}


/*
  作業内容
*/
Table t_works {
  id integer [primary key]
  name varchar(100) [not null]
  description text
}


/*
  作業時間
*/
Table t_work_logs {
  id integer [primary key]
  user_id integer [not null, ref: > t_users.id]
  work_type_id integer [not null, ref: > t_works.id]
  date date [not null]
  total_minutes bigint [not null, default: 0]
  created_at timestamp
  updated_at timestamp
}

