name: API Test with Postman & Newman

on:
  push:
    branches:
      - main
      - development-main-*
  pull_request:
    branches:
      - main
      - development-main-*

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env file from secrets
        run: |
          echo "TIME_ZONE=${{ secrets.TIME_ZONE }}" > .env
          echo "JWT_TOKEN_LIFE_SPAN=${{ secrets.JWT_TOKEN_LIFE_SPAN }}" >> .env
          echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> .env
          echo "ENVIRONMENT=${{ secrets.ENVIRONMENT }}" >> .env
          echo "ADMIN_EMAIL=${{ secrets.ADMIN_EMAIL }}" >> .env
          echo "ADMIN_EMAIL_PASSWORD=${{ secrets.ADMIN_EMAIL_PASSWORD }}" >> .env
          echo "ADMIN_USERNAME=${{ secrets.ADMIN_USERNAME }}" >> .env
          echo "ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}" >> .env
          echo "MINUTES_PER_INTERVAL=${{ secrets.MINUTES_PER_INTERVAL }}" >> .env
          echo "COIN_COUNT_PER_INTERVAL=${{ secrets.COIN_COUNT_PER_INTERVAL }}" >> .env
          echo "OTP_DEADLINE=${{ secrets.OTP_DEADLINE }}" >> .env
          echo "BACKEND_PORT=${{ secrets.BACKEND_PORT }}" >> .env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
          echo "POSTGRES_GENERAL_USER=${{ secrets.POSTGRES_GENERAL_PASSWORD }}" >> .env
          echo "DATABASE_HOST=${{ secrets.DATABASE_HOST }}" >> .env
          echo "DATABASE_PORT=${{ secrets.DATABASE_PORT }}" >> .env


      - name: Start app
        run: |
          docker compose up --build -d
          until docker compose ps | grep -q "healthy"; do
            echo "Waiting for services to be healthy..."
            sleep 5
          done
          echo "Services are up and running."

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Newman
        run: npm install -g newman

      - name: Test Admin API
        run: newman run ./postman/admin.json --reporters cli,junit --reporter-junit-export results.xml --env-var ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}

      - name: Test Auth API
        run: newman run ./postman/auth.json --reporters cli,junit --reporter-junit-export results.xml

      - name: Test Study Room API
        run: newman run ./postman/study_room.json --reporters cli,junit --reporter-junit-export results.xml

      - name: Test Work API
        run: newman run ./postman/work.json --reporters cli,junit --reporter-junit-export results.xml

      - name: Test Profile API
        run: newman run ./postman/profile.json --reporters cli,junit --reporter-junit-export results.xml

      - name: Test Friend API
        run: newman run ./postman/friend.json --reporters cli,junit --reporter-junit-export results.xml

      - name: Test Buildings API
        run: newman run ./postman/buildings.json --reporters cli,junit --reporter-junit-export results.xml

      - name: Test Store API
        run: newman run ./postman/store.json --reporters cli,junit --reporter-junit-export results.xml

      - name: Test Characters API
        run: newman run ./postman/characters.json --reporters cli,junit --reporter-junit-export results.xml

      - name: Test Password API
        run: newman run ./postman/password.json --reporters cli,junit --reporter-junit-export results.xml

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install -r ./tools/websocket_client/requirements.txt

      - name: Run WebSocket API test
        run: python ./tools/websocket_client/websocket_client.py

      - name: Show logs from backend-go (before test)
        if: always()
        run: |
          echo "===== BACKEND-GO LOGS (Before Test) ====="
          docker compose logs backend-go

      - name: Stop app
        run: docker compose down -v